"""create HTE and MOA tables

Revision ID: 1128d97f6166
Revises: aeb611068500
Create Date: 2026-01-29 08:13:18.310838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1128d97f6166'
down_revision = 'aeb611068500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_training_establishments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memoranda_of_agreement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hte_id', sa.Integer(), nullable=False),
    sa.Column('signed_at', sa.Date(), nullable=False),
    sa.Column('expires_at', sa.Date(), nullable=False),
    sa.Column('document_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'EXPIRED', name='moa_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hte_id'], ['host_training_establishments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memoranda_of_agreement')
    op.drop_table('host_training_establishments')
    # ### end Alembic commands ###
