"""add thumbnail_path to hte

Revision ID: 4a1ba56ca97f
Revises: 7046b1b65867
Create Date: 2026-01-30 03:19:40.681987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a1ba56ca97f'
down_revision = '7046b1b65867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host_training_establishments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host_training_establishments', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_path')

    # ### end Alembic commands ###
