"""create host_training_establishments table

Revision ID: 7046b1b65867
Revises: 1128d97f6166
Create Date: 2026-01-29 08:18:13.757016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7046b1b65867'
down_revision = '1128d97f6166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host_training_establishments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('contact_person', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('contact_position', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('contact_email', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('moa_status', sa.Enum('ACTIVE', 'PENDING', 'EXPIRED', name='moa_status_enum'), nullable=False))
        batch_op.add_column(sa.Column('course', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('moa_signed_at', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('moa_validity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('moa_expiry_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('moa_file_path', sa.String(length=255), nullable=True))
        batch_op.alter_column('industry',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('description')
        batch_op.drop_column('website')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('host_training_establishments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('website', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('industry',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('moa_file_path')
        batch_op.drop_column('moa_expiry_date')
        batch_op.drop_column('moa_validity')
        batch_op.drop_column('moa_signed_at')
        batch_op.drop_column('course')
        batch_op.drop_column('moa_status')
        batch_op.drop_column('contact_email')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('contact_position')
        batch_op.drop_column('contact_person')
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
