"""profiles

Revision ID: aeb611068500
Revises: 16c1b7d42254
Create Date: 2026-01-16 06:01:16.255290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb611068500'
down_revision = '16c1b7d42254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('admin_id', sa.String(length=100), nullable=True),
    sa.Column('admin_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_profiles_user_id'), ['user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_profiles_username'), ['username'], unique=True)

    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_initial', sa.String(length=5), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profiles_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_user_id'))

    op.drop_table('student_profiles')
    with op.batch_alter_table('admin_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_profiles_username'))
        batch_op.drop_index(batch_op.f('ix_admin_profiles_user_id'))

    op.drop_table('admin_profiles')
    # ### end Alembic commands ###
